// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: capture.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockRuleTargetType int32

const (
	BlockRuleTargetType_BLOCK_RULE_TARGET_TYPE_UNSPECIFIED BlockRuleTargetType = 0
	BlockRuleTargetType_BLOCK_RULE_TARGET_TYPE_IP          BlockRuleTargetType = 1
	BlockRuleTargetType_BLOCK_RULE_TARGET_TYPE_CIDR        BlockRuleTargetType = 2
	BlockRuleTargetType_BLOCK_RULE_TARGET_TYPE_SNI         BlockRuleTargetType = 3
)

// Enum value maps for BlockRuleTargetType.
var (
	BlockRuleTargetType_name = map[int32]string{
		0: "BLOCK_RULE_TARGET_TYPE_UNSPECIFIED",
		1: "BLOCK_RULE_TARGET_TYPE_IP",
		2: "BLOCK_RULE_TARGET_TYPE_CIDR",
		3: "BLOCK_RULE_TARGET_TYPE_SNI",
	}
	BlockRuleTargetType_value = map[string]int32{
		"BLOCK_RULE_TARGET_TYPE_UNSPECIFIED": 0,
		"BLOCK_RULE_TARGET_TYPE_IP":          1,
		"BLOCK_RULE_TARGET_TYPE_CIDR":        2,
		"BLOCK_RULE_TARGET_TYPE_SNI":         3,
	}
)

func (x BlockRuleTargetType) Enum() *BlockRuleTargetType {
	p := new(BlockRuleTargetType)
	*p = x
	return p
}

func (x BlockRuleTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockRuleTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_capture_proto_enumTypes[0].Descriptor()
}

func (BlockRuleTargetType) Type() protoreflect.EnumType {
	return &file_capture_proto_enumTypes[0]
}

func (x BlockRuleTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockRuleTargetType.Descriptor instead.
func (BlockRuleTargetType) EnumDescriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBlockRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRulesRequest) Reset() {
	*x = GetBlockRulesRequest{}
	mi := &file_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRulesRequest) ProtoMessage() {}

func (x *GetBlockRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRulesRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRulesRequest) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{2}
}

type BlockRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceMac     string                 `protobuf:"bytes,3,opt,name=device_mac,json=deviceMac,proto3" json:"device_mac,omitempty"`
	DeviceIp      string                 `protobuf:"bytes,4,opt,name=device_ip,json=deviceIp,proto3" json:"device_ip,omitempty"`
	DeviceLabel   string                 `protobuf:"bytes,5,opt,name=device_label,json=deviceLabel,proto3" json:"device_label,omitempty"`
	TargetType    BlockRuleTargetType    `protobuf:"varint,6,opt,name=target_type,json=targetType,proto3,enum=capture_receiver.BlockRuleTargetType" json:"target_type,omitempty"`
	TargetValue   string                 `protobuf:"bytes,7,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRule) Reset() {
	*x = BlockRule{}
	mi := &file_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRule) ProtoMessage() {}

func (x *BlockRule) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRule.ProtoReflect.Descriptor instead.
func (*BlockRule) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{3}
}

func (x *BlockRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockRule) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BlockRule) GetDeviceMac() string {
	if x != nil {
		return x.DeviceMac
	}
	return ""
}

func (x *BlockRule) GetDeviceIp() string {
	if x != nil {
		return x.DeviceIp
	}
	return ""
}

func (x *BlockRule) GetDeviceLabel() string {
	if x != nil {
		return x.DeviceLabel
	}
	return ""
}

func (x *BlockRule) GetTargetType() BlockRuleTargetType {
	if x != nil {
		return x.TargetType
	}
	return BlockRuleTargetType_BLOCK_RULE_TARGET_TYPE_UNSPECIFIED
}

func (x *BlockRule) GetTargetValue() string {
	if x != nil {
		return x.TargetValue
	}
	return ""
}

func (x *BlockRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetBlockRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*BlockRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	GeneratedAt   int64                  `protobuf:"varint,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRulesResponse) Reset() {
	*x = GetBlockRulesResponse{}
	mi := &file_capture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRulesResponse) ProtoMessage() {}

func (x *GetBlockRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRulesResponse.ProtoReflect.Descriptor instead.
func (*GetBlockRulesResponse) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockRulesResponse) GetRules() []*BlockRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *GetBlockRulesResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

var File_capture_proto protoreflect.FileDescriptor

const file_capture_proto_rawDesc = "" +
	"\n" +
	"\rcapture.proto\x12\x10capture_receiver\"]\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"`\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x16\n" +
	"\x14GetBlockRulesRequest\"\x9c\x02\n" +
	"\tBlockRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"device_mac\x18\x03 \x01(\tR\tdeviceMac\x12\x1b\n" +
	"\tdevice_ip\x18\x04 \x01(\tR\bdeviceIp\x12!\n" +
	"\fdevice_label\x18\x05 \x01(\tR\vdeviceLabel\x12F\n" +
	"\vtarget_type\x18\x06 \x01(\x0e2%.capture_receiver.BlockRuleTargetTypeR\n" +
	"targetType\x12!\n" +
	"\ftarget_value\x18\a \x01(\tR\vtargetValue\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"m\n" +
	"\x15GetBlockRulesResponse\x121\n" +
	"\x05rules\x18\x01 \x03(\v2\x1b.capture_receiver.BlockRuleR\x05rules\x12!\n" +
	"\fgenerated_at\x18\x02 \x01(\x03R\vgeneratedAt*\x9d\x01\n" +
	"\x13BlockRuleTargetType\x12&\n" +
	"\"BLOCK_RULE_TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19BLOCK_RULE_TARGET_TYPE_IP\x10\x01\x12\x1f\n" +
	"\x1bBLOCK_RULE_TARGET_TYPE_CIDR\x10\x02\x12\x1e\n" +
	"\x1aBLOCK_RULE_TARGET_TYPE_SNI\x10\x032\x91\x02\n" +
	"\rPacketGateway\x12L\n" +
	"\rPublishPacket\x12\x18.capture_receiver.Packet\x1a!.capture_receiver.PublishResponse\x12P\n" +
	"\rStreamPackets\x12\x18.capture_receiver.Packet\x1a!.capture_receiver.PublishResponse(\x010\x01\x12`\n" +
	"\rGetBlockRules\x12&.capture_receiver.GetBlockRulesRequest\x1a'.capture_receiver.GetBlockRulesResponseB2Z0github.com/nrf24l01/sniffly/capturer/proto;protob\x06proto3"

var (
	file_capture_proto_rawDescOnce sync.Once
	file_capture_proto_rawDescData []byte
)

func file_capture_proto_rawDescGZIP() []byte {
	file_capture_proto_rawDescOnce.Do(func() {
		file_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capture_proto_rawDesc), len(file_capture_proto_rawDesc)))
	})
	return file_capture_proto_rawDescData
}

var file_capture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_capture_proto_goTypes = []any{
	(BlockRuleTargetType)(0),      // 0: capture_receiver.BlockRuleTargetType
	(*Packet)(nil),                // 1: capture_receiver.Packet
	(*PublishResponse)(nil),       // 2: capture_receiver.PublishResponse
	(*GetBlockRulesRequest)(nil),  // 3: capture_receiver.GetBlockRulesRequest
	(*BlockRule)(nil),             // 4: capture_receiver.BlockRule
	(*GetBlockRulesResponse)(nil), // 5: capture_receiver.GetBlockRulesResponse
}
var file_capture_proto_depIdxs = []int32{
	0, // 0: capture_receiver.BlockRule.target_type:type_name -> capture_receiver.BlockRuleTargetType
	4, // 1: capture_receiver.GetBlockRulesResponse.rules:type_name -> capture_receiver.BlockRule
	1, // 2: capture_receiver.PacketGateway.PublishPacket:input_type -> capture_receiver.Packet
	1, // 3: capture_receiver.PacketGateway.StreamPackets:input_type -> capture_receiver.Packet
	3, // 4: capture_receiver.PacketGateway.GetBlockRules:input_type -> capture_receiver.GetBlockRulesRequest
	2, // 5: capture_receiver.PacketGateway.PublishPacket:output_type -> capture_receiver.PublishResponse
	2, // 6: capture_receiver.PacketGateway.StreamPackets:output_type -> capture_receiver.PublishResponse
	5, // 7: capture_receiver.PacketGateway.GetBlockRules:output_type -> capture_receiver.GetBlockRulesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_capture_proto_init() }
func file_capture_proto_init() {
	if File_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capture_proto_rawDesc), len(file_capture_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capture_proto_goTypes,
		DependencyIndexes: file_capture_proto_depIdxs,
		EnumInfos:         file_capture_proto_enumTypes,
		MessageInfos:      file_capture_proto_msgTypes,
	}.Build()
	File_capture_proto = out.File
	file_capture_proto_goTypes = nil
	file_capture_proto_depIdxs = nil
}
