// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: capture.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PacketGateway_PublishPacket_FullMethodName = "/capture_receiver.PacketGateway/PublishPacket"
	PacketGateway_StreamPackets_FullMethodName = "/capture_receiver.PacketGateway/StreamPackets"
	PacketGateway_GetBlockRules_FullMethodName = "/capture_receiver.PacketGateway/GetBlockRules"
)

// PacketGatewayClient is the client API for PacketGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PacketGatewayClient interface {
	PublishPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*PublishResponse, error)
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, PublishResponse], error)
	GetBlockRules(ctx context.Context, in *GetBlockRulesRequest, opts ...grpc.CallOption) (*GetBlockRulesResponse, error)
}

type packetGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPacketGatewayClient(cc grpc.ClientConnInterface) PacketGatewayClient {
	return &packetGatewayClient{cc}
}

func (c *packetGatewayClient) PublishPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PacketGateway_PublishPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packetGatewayClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PacketGateway_ServiceDesc.Streams[0], PacketGateway_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PacketGateway_StreamPacketsClient = grpc.BidiStreamingClient[Packet, PublishResponse]

func (c *packetGatewayClient) GetBlockRules(ctx context.Context, in *GetBlockRulesRequest, opts ...grpc.CallOption) (*GetBlockRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockRulesResponse)
	err := c.cc.Invoke(ctx, PacketGateway_GetBlockRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PacketGatewayServer is the server API for PacketGateway service.
// All implementations must embed UnimplementedPacketGatewayServer
// for forward compatibility.
type PacketGatewayServer interface {
	PublishPacket(context.Context, *Packet) (*PublishResponse, error)
	StreamPackets(grpc.BidiStreamingServer[Packet, PublishResponse]) error
	GetBlockRules(context.Context, *GetBlockRulesRequest) (*GetBlockRulesResponse, error)
	mustEmbedUnimplementedPacketGatewayServer()
}

// UnimplementedPacketGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPacketGatewayServer struct{}

func (UnimplementedPacketGatewayServer) PublishPacket(context.Context, *Packet) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPacket not implemented")
}
func (UnimplementedPacketGatewayServer) StreamPackets(grpc.BidiStreamingServer[Packet, PublishResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedPacketGatewayServer) GetBlockRules(context.Context, *GetBlockRulesRequest) (*GetBlockRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockRules not implemented")
}
func (UnimplementedPacketGatewayServer) mustEmbedUnimplementedPacketGatewayServer() {}
func (UnimplementedPacketGatewayServer) testEmbeddedByValue()                       {}

// UnsafePacketGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacketGatewayServer will
// result in compilation errors.
type UnsafePacketGatewayServer interface {
	mustEmbedUnimplementedPacketGatewayServer()
}

func RegisterPacketGatewayServer(s grpc.ServiceRegistrar, srv PacketGatewayServer) {
	// If the following call pancis, it indicates UnimplementedPacketGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PacketGateway_ServiceDesc, srv)
}

func _PacketGateway_PublishPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacketGatewayServer).PublishPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PacketGateway_PublishPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacketGatewayServer).PublishPacket(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacketGateway_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PacketGatewayServer).StreamPackets(&grpc.GenericServerStream[Packet, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PacketGateway_StreamPacketsServer = grpc.BidiStreamingServer[Packet, PublishResponse]

func _PacketGateway_GetBlockRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacketGatewayServer).GetBlockRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PacketGateway_GetBlockRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacketGatewayServer).GetBlockRules(ctx, req.(*GetBlockRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PacketGateway_ServiceDesc is the grpc.ServiceDesc for PacketGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacketGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capture_receiver.PacketGateway",
	HandlerType: (*PacketGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishPacket",
			Handler:    _PacketGateway_PublishPacket_Handler,
		},
		{
			MethodName: "GetBlockRules",
			Handler:    _PacketGateway_GetBlockRules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _PacketGateway_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "capture.proto",
}
