// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: capture.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PacketGateway_PublishPacket_FullMethodName = "/capture_receiver.PacketGateway/PublishPacket"
	PacketGateway_StreamPackets_FullMethodName = "/capture_receiver.PacketGateway/StreamPackets"
)

// PacketGatewayClient is the client API for PacketGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PacketGatewayClient interface {
	PublishPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*PublishResponse, error)
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (PacketGateway_StreamPacketsClient, error)
}

type packetGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPacketGatewayClient(cc grpc.ClientConnInterface) PacketGatewayClient {
	return &packetGatewayClient{cc}
}

func (c *packetGatewayClient) PublishPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PacketGateway_PublishPacket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packetGatewayClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (PacketGateway_StreamPacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PacketGateway_ServiceDesc.Streams[0], PacketGateway_StreamPackets_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &packetGatewayStreamPacketsClient{stream}
	return x, nil
}

type PacketGateway_StreamPacketsClient interface {
	Send(*Packet) error
	Recv() (*PublishResponse, error)
	grpc.ClientStream
}

type packetGatewayStreamPacketsClient struct {
	grpc.ClientStream
}

func (x *packetGatewayStreamPacketsClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *packetGatewayStreamPacketsClient) Recv() (*PublishResponse, error) {
	m := new(PublishResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PacketGatewayServer is the server API for PacketGateway service.
// All implementations must embed UnimplementedPacketGatewayServer
// for forward compatibility
type PacketGatewayServer interface {
	PublishPacket(context.Context, *Packet) (*PublishResponse, error)
	StreamPackets(PacketGateway_StreamPacketsServer) error
	mustEmbedUnimplementedPacketGatewayServer()
}

// UnimplementedPacketGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedPacketGatewayServer struct {
}

func (UnimplementedPacketGatewayServer) PublishPacket(context.Context, *Packet) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPacket not implemented")
}
func (UnimplementedPacketGatewayServer) StreamPackets(PacketGateway_StreamPacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedPacketGatewayServer) mustEmbedUnimplementedPacketGatewayServer() {}

// UnsafePacketGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacketGatewayServer will
// result in compilation errors.
type UnsafePacketGatewayServer interface {
	mustEmbedUnimplementedPacketGatewayServer()
}

func RegisterPacketGatewayServer(s grpc.ServiceRegistrar, srv PacketGatewayServer) {
	s.RegisterService(&PacketGateway_ServiceDesc, srv)
}

func _PacketGateway_PublishPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacketGatewayServer).PublishPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PacketGateway_PublishPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacketGatewayServer).PublishPacket(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

func _PacketGateway_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PacketGatewayServer).StreamPackets(&packetGatewayStreamPacketsServer{stream})
}

type PacketGateway_StreamPacketsServer interface {
	Send(*PublishResponse) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type packetGatewayStreamPacketsServer struct {
	grpc.ServerStream
}

func (x *packetGatewayStreamPacketsServer) Send(m *PublishResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *packetGatewayStreamPacketsServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PacketGateway_ServiceDesc is the grpc.ServiceDesc for PacketGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacketGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capture_receiver.PacketGateway",
	HandlerType: (*PacketGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishPacket",
			Handler:    _PacketGateway_PublishPacket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _PacketGateway_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "capture.proto",
}
