@startuml arch
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam arrowColor #666666

!define TECH(x) <b>x</b>

package "Sniffly" {
    database "База данных(postgres)" as db #1869ff
    queue "Очередь сообщений(rabbitmq)" as queue #FC6D26
    database "База кеша(redis)" as redis #D82C20

    [Приемник захвата] as capture_receiver #00ADD8
    [Бэкенд] as backend #00ADD8
    [Модуль анализа] as analysis #00ADD8
    [Фронтенд] as frontend #42b883
    [Nginx] as nginx #009639
}

package "Шлюзы(устройства куда ставится захватывать)" {
    [Модуль захвата] as capture #00ADD8
    [Модуль захвата 1] as capture1 #00ADD8
}

analysis <--> redis : GeoIP кеш
frontend --> nginx : HTTP API
nginx <--> backend : HTTP API
backend --> db : Запрос\nданных для отчетов
analysis -> db : Сохранение\nрезультатов анализа
backend --> db : Сохранение и\nзапрос данных
backend <--> redis : Кеширование\nстарых отчетов
capture --> nginx : Отправка\nзахваченных пакетов
capture1 --> nginx : Отправка\nзахваченных пакетов
nginx <--> capture_receiver : Передача\nзахваченных пакетов\n(gRPC)
capture_receiver -> db : Кому можно сохранять
capture_receiver -> queue : Помещение пакетов\nв очередь на анализ
analysis <- queue : Получение пакетов\nдля анализа
@enduml