@startuml arch
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam arrowColor #666666

skinparam ranksep 60
skinparam nodesep 10

top to bottom direction

package "Gateways" as gateways {
    [Capturer] as capture #00ADD8
    [Capturer 1] as capture1 #00ADD8
}

!define TECH(x) <b>x</b>

package "Sniffly" as sniffly {
    database "Database (Postgres)" as db #1869ff
    queue "Packet Queue (RabbitMQ)" as queue #FC6D26
    database "Cache Database (Redis)" as redis #D82C20

    [Capture Receiver] as capture_receiver #00ADD8
    [Backend] as backend #00ADD8
    [Analysis Module] as analysis #00ADD8
    [Frontend] as frontend #42b883
    [Nginx] as nginx #009639
}

gateways -down[hidden]-> sniffly
gateways -[hidden]-> sniffly

frontend -down[hidden]-> nginx
nginx -down[hidden]-> backend
backend -down[hidden]-> db
nginx -down[hidden]-> capture_receiver
capture_receiver -down[hidden]-> queue
queue -down[hidden]-> analysis
analysis -down[hidden]-> redis

analysis <-down-> redis : GeoIP cache
frontend -down-> nginx : HTTP API
nginx <-down-> backend : HTTP API
backend --> db : Query\ndata for reports
analysis -> db : Save\nanalysis results
backend --> db : Save and\nquery data
backend <--> redis : Cache\nold reports
capture -down-> nginx : Send\ncaptured packets\n(gRPC)
capture1 -down-> nginx : Send\ncaptured packets\n(gRPC)
nginx <-down-> capture_receiver : Send\ncaptured packets\n(gRPC)
capture_receiver -> db : Check capturer auth
capture_receiver -> queue : Enqueue packets\nfor analysis
queue -down-> analysis : Dequeue packets\nfor analysis
@enduml