@startuml project
@startmindmap
* Sniffly
** Разработка
*** Написать модуль захвата (Go)
*** Написать модуль анализа (Go)
*** Написать бэкенд (Go)
*** Написать фронтенд (Vue.js)
*** Удобная система запуска (docker)
** Аналитическая (классифицировать трафик)
*** Собрать трафик
*** Разделить по типам запросов
*** Извлечь необходимую информацию
@endmindmap
@enduml